### ISSUE TITLE
How to destroy session with closing browser in ion auth and how to set expiry time

### ISSUE THREAD

**Issue by vinodkumar899** [benedmunds/CodeIgniter-Ion-Auth#1056]
I have used ion auth api in codeigniter but when i closed the browser ,again browser will be open session not expiry it will shows the results

**Comment by benedmunds** [comment]
You can try setting this in your CI config:
$config['sess_expire_on_close'] = TRUE;

You may have to use Javascript to call logout on browser unload.  Here's a SO that explain how to do it: http://stackoverflow.com/questions/13174297/how-to-destroy-session-with-browser-closing-in-codeigniter

FYI this would be weird behavior, users will expect to remain logged in if they have a valid session even after browser close.
