### ISSUE TITLE
So many users 'double click' the password reset link

### ISSUE THREAD

**Issue by nathanpitman** [benedmunds/CodeIgniter-Ion-Auth#1082]
This is a real problem. We have upwards of 800k users and we're finding that a common issue is that many 'older users' still 'double click' links. This invalidates the password reset on the first request and then when the page loads fully they are presented with an error advising that the password reset request is not valid.

Thoughts? We're considering options such as a toggle to allow 2 uses before invalidating, or invalidation after a specified time with unlimited uses.

Thoughts?

**Comment by benedmunds** [comment]
Hey,

Just want to clarify, they are double clicking from their email? Which
probably opens two tabs in their browser and invalidates the link.  Is that
correct?

-Ben Edmunds

**Comment by avenirer** [comment]
I wouldn't intervene, as this is the result of users misusing internet.

**Comment by nathanpitman** [comment]
Correct, that's exactly what's happening.

**Comment by nathanpitman** [comment]
Yes it IS the result of a misunderstanding of how things work, however the
end result is that the user is frustrated and does not understand why this
stupid web app won't let him/her reset his/her password.

This isn't something new, and the reality is that it shouldn't be for the
user to understand, we need to do what we can as developers to reduce
friction with such processes and make it easy for the end user, regardless
of their competency. :)

**Comment by gpotter** [comment]
I've seen where developers use a loop to catch if the page is open in other
tabs or windows and throws an alert saying it is open in another window and
a link to the 'active' session  window.  Would require jscript  so not sure
if that would work.

**Comment by avenirer** [comment]
Why not make an intermediary page where you put a link and add the reset code as parameter. This way you force the users to click on that link in order to finish resetting​ the password.

**Comment by benedmunds** [comment]
An intermediary page is the best suggestion I can think of as well.  Otherwise you'll want to modify the core library logic in some way.  The best way would probably be to add a field for an invalidation timestamp of the hash and then allow the link to be used until that invalidation timestamp is X minutes old...  Another way to solve it would be to have a separate table of hashes.

**Comment by benedmunds** [comment]
This isnt something I'd like to condone in the core library offering, since it is generally bad practice and less secure.  Although, I do understand why you might want to modify to support this since it is a problem for your users.

Feel free to reach out if you need need help implementing a solution.
