### ISSUE TITLE
ION_AUTH using SQL Server 2014

### ISSUE THREAD

**Issue by wayahnawe** [benedmunds/CodeIgniter-Ion-Auth#1136]
Hi.. 

This 1st time i'm using ION_AUTH with MSSQL Server. I can connect to database but after i login, i have this database error 
Error Number: 22003/8115

[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Arithmetic overflow error converting expression to data type datetime.

SELECT 1 FROM "login_attempts" WHERE "login" = 'admin@admin.com' AND "ip_address" = '::1' AND time >1506106447

Filename: C:/xampp/htdocs/optrans/system/database/DB_driver.php

Line Number: 691

**Comment by benedmunds** [comment]
Looks like this line in the SQL server login_attempts creation statement is incorrect:

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/2/sql/ion_auth.mssql.sql#L65


I don't use SQL server so I'm not sure what is best here but an integer type should do the trick as this is just storing seconds since epoch.  The postgres setup uses "int" and the mysql setup uses "int(11).

Let me know what works for you and I'll update the SQL server setup file in the repo, or send a PR and I'll merge.

Thanks!

**Comment by wayahnawe** [comment]
Hi Bene..

After i recreate column and change datatype  from datetime to int. It work 

Thanks

**Comment by benedmunds** [comment]
Thanks, I committed that change back as well!
