### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by maneeshms** [benedmunds/CodeIgniter-Ion-Auth#1171]
Is there any chance for mongodb support in Ion Auth?

**Comment by benedmunds** [comment]
Ion Auth used to support Mongo actually.  I removed it a couple years ago because it was difficult to keep up with changes and since I don’t use Mongo personally I didn’t feel like I could ensure it worked properly for all changes.

You can check out how it used to work here https://github.com/benedmunds/CodeIgniter-Ion-Auth/tree/dd57a96d701a16a052aa5858a9ad50a9724369da

This is the last commit before it was removed.  It should give you a good starting place.

**Comment by maneeshms** [comment]
Thank you.... This is a good start for me... I will develop my logics on this ...
