### ISSUE TITLE
user_groups table vs group id in user table

### ISSUE THREAD

**Issue by engineertdog** [benedmunds/CodeIgniter-Ion-Auth#1179]
Performance wise, what's the difference between using a table dubbed "users_groups" to keep track of the groups a user is assigned to versus keeping track of them in a column in the users table?

Personally, I'd prefer the latter.

On a similar note, I prefer grabbing information from the database in an ID based way as much as possible, for certain things. So, for the config values of 
```
$config['default_group']
$config['admin_group']
```
What is the possibility of making them ID based rather than name based?

**Comment by benedmunds** [comment]
I would think that a column would be slower, since you can add foreign keys to join from with a relation table.  I'm not aware of a performant way (in relational databases) to join using multiple values in a column, although some databases may have a way to accomplish that.

Add an index to the group name field if you're worried about performance there.  

If you're having performance issues then adding foreign keys and indexing is the first thing I'd recommend.  

If you're getting to the point where micro optimizations are making a huge difference then you'll probably want to rip out a lot of the CI query builder work in general and write your own queries for everything.
