### ISSUE TITLE
How to login without password

### ISSUE THREAD

**Issue by Narendraoms** [benedmunds/CodeIgniter-Ion-Auth#1189]
Hello All
I want to login through social media like facebook 
so i need to login without password can any one suggest how it possible or any method

Thanks in advance

**Comment by avenirer** [comment]
I don't know if this method still works, but you can try on of my tutorials: http://avenir.ro/authentication-system-with-ion-auth-and-ci3/login-register-facebook-ion-auth/

**Comment by simmonspaul** [comment]
I noticed that this question has been asked a couple of times and each time it is closed due to potential security concerns - understandable.

I'm loving Ion-Auth and also in the past happened upon Avenirer's tutorials which are also helpful.

I decided to use HybridAuth for social media logins as it is very comprehensive. On a successful callback from a social media login I want to have the user logged into Ion-Auth.

This is my hack...
*On the successful callback from social media obtain the user email.
*Check to see if this email exists in the ion_auth users table.
(Previously modified the ion_auth users table with one extra varchar(255) field called password_bump)
*If the email exists then copy their existing password to password_bump.
*Copy the encoded string representing eg. 'test' to their password field.
*Log the user into ion_auth using their email address and 'test'.
*Change their password field in the user table back to what it was originally.

public function email_force_login($email)
                {
// get the user record based on provided email address
        $this->db->select('*');
        $this->db->from('users');
        $this->db->where('email',$email);
        $this->db->where('active','1');
        $query=$this->db->get();       
        $result = $query->row();       
// if it is found then do stuff
            if($query->num_rows()>0){
                $result = $query->row();
// this is the stored password in the users table
                $user_password = $result->password;
// copy their password to the password_bump field that was added to the users table
        $this->db->set('password_bump', $user_password);
        $this->db->where('email',$email);
        $this->db->where('active','1');    
        $this->db->update('users'); 
// insert a encrypted string in their password that you know the result of eg 'test'
        $this->db->set('password', '$2y$08$GxqUneCiftgOKf9xJ8LubOmOfnwBkFG.sDLCpIpp4gUuV1fb3gNFm');
        $this->db->where('email',$email);
        $this->db->where('active','1');    
        $this->db->update('users'); 
// log the user into ion_auth as normal                
        $this->login($email, 'test', TRUE);
// change their password back to what it was originally 
        $this->db->set('password', $user_password);
        $this->db->where('email',$email);
        $this->db->where('active','1');    
        $this->db->update('users'); 
// Could but I didn't blank out the 'bump' field
        return TRUE; 
            }
// email not found don't do stuff
else{
                return FALSE;
            }
                }

**Comment by mhamzas** [comment]
@simmonspaul Thanks. It worked.
