### ISSUE TITLE
Support / Ability to switch hashing method

### ISSUE THREAD

**Issue by janvanrijn** [benedmunds/CodeIgniter-Ion-Auth#1289]
In our application, due to initial (bad) design constraints we stored the passwords of users using a weak hashing algorithm, and did not use salt. Now our application is running for several years stable, and with a huge userbase, we would like to change this (without requiring users to update their password), but this requires some book keeping and an intermediate step. 

It seems that IonAuth does currently does not support this use-case. I am happy to create a PR for this (on medium term) if this functionality is desirable. 

cc: https://github.com/openml/OpenML/issues/883

**Comment by benedmunds** [comment]
Hey,

Which version are you on?

Version 3+ support this ootb.

**Comment by janvanrijn** [comment]
Thanks for your quick reply! 

Which branch do I download that from? I am guessing "3"? Or should I go ahead and download "4" immediately?

**Comment by benedmunds** [comment]
Yea you get them from the branches but they should usually match the CodeIgniter version you’re using.  Ion Auth 2 works for CI2 and CI3 though.

Looking at your link, looks like you were on Ion Auth 2 and using MD5. This complicates things a bit since Ion Auth 3 doesn’t support MD5.

What I would recommend is sticking with Ion Auth 2 for right now and doing the following:

Backup your DB
Increase your password field length if needed (recommend varchar(254) for future proofing.
Write a script to loop through your DB and do a BCrypt hash on the existing MD5 hash’s.
Update your Ion Auth config to use BCrypt and to match the BCrypt settings used above.
In your controllers, anywhere that you currently pass a plaintext password to Ion Auth, instead md5 it first (register/login/password reset/etc).


The advantage of the above to a tranditional, upgrade to new hash as users login, method is that you immediately have more secure hashing on your stored passwords.

If you can’t do the above, maybe because you don’t have access to the databases or in order to make the process simpler for your users, then a traditional upgrade as users login method is preferred.  If you want to do a PR for this against the 2 branch I’d greatly appreciate it, just be mindful of backwards compatibility.

**Comment by janvanrijn** [comment]
> Looking at your link, looks like you were on Ion Auth 2 and using MD5. This complicates things a bit since Ion Auth 3 doesn’t support MD5.

I once added this single feature to my copy of IonAuth to support MD5 in line with our (bad) design choice. I actually wanted to get rid of this added MD5 support, as it will complicate further `Ion_auth` upgrades. 

Personally, the best way to get rid of this MD5 option is to upgrade to 3 anyway, and replace the `_password_verify_sha1_legacy` with custom code `_password_verify_md5_legacy`. 

If my code could be used in any way in a PR, I'd be happy to contribute, but I think that general users do not have any use for md5 legacy. 

Thanks again for the great work on this awesome library!

**Comment by janvanrijn** [comment]
One more related question: 

```
$this->trigger_events(['post_sha1_password_migration', 'post_sha1_password_migration_successful']);
```

This seems to call to a hook. Where can I find these?

**Comment by benedmunds** [comment]
Ah ok cool, agreed then that a PR probably wouldn’t be widely needed so probably not worth the extra effort.

Jeff has a good tutorial on using the hooks here: 
http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth

**Comment by janvanrijn** [comment]
> Ah ok cool, agreed then that a PR probably wouldn’t be widely needed so probably not worth the extra effort.

Just for the record, I am happy to put in the additional effort (it's only fair, for getting to use `Ion_Auth`) but the reason why I wouldn't add it upstream is because I am probably the only user using `md5` (not sure if it was ever an official feature). Let me know if you would like me to add it anyway. 

> Jeff has a good tutorial on using the hooks here:
http://codebyjeff.com/blog/2013/01/using-hooks-with-ion_auth

Cool! What I get from it is that the hooks are tricks to trigger additional "user-defined" code, in such a way that I won't encounter them in the `Ion_auth` code, but potentially in my own `hooks` folder if I had ever defined it.

**Comment by benedmunds** [comment]
Nah I don’t think it’s needed, MD5 used to be supported but isn’t been in awhile now.

Yea that’s a fair description, they’re a way to run your own custom code without modifying the library files. Makes upgrading easier.

**Comment by janvanrijn** [comment]
Thanks for the support, really appreciated!

**Comment by benedmunds** [comment]
No problem, hope it goes smoothly!
