### ISSUE TITLE
use_ci_email

### ISSUE THREAD

**Issue by srok** [benedmunds/CodeIgniter-Ion-Auth#1341]
Looks like default email config is being overridden when initializing on:
`if ($this->config->item('use_ci_email', 'ion_auth') && isset($email_config) && is_array($email_config))
		{
			$this->email->initialize($email_config);
		}`
In my case, I'm loading the config file like this:
`$config['email_config'] = get_instance()->load->config('email',TRUE);`
instread of
` $config['email_config'] = array(
 	'mailtype' => 'html',
 );`

**Comment by benedmunds** [comment]
Why are you loading it that why?  Do you need it returned back or something?

**Comment by srok** [comment]
This way I keep the rest of the code unmodified. Otherwise, the rest of the settings present in config/email.php won't be passed to email->initialize

**Comment by benedmunds** [comment]
Ah, if you set ```$config['email_config'] = null ``` it should just use your config/email.php settings.

**Comment by srok** [comment]
Or maybe the arrays could be merged, overriding config/email.php with $config['email_config']

**Comment by benedmunds** [comment]
yea thats a great idea, want to tackle a PR for that?

**Comment by srok** [comment]
Ok, no problem.

**Comment by benedmunds** [comment]
Awesome, thanks!

**Comment by reno3131** [comment]
I believe this issue is not closed, there is still errors : 
I believe this : `$this->email->initialize(array_merge($ci_email_config,(array)$email_config));`
should be : `$this->email->initialize(array_merge($this->config->item('email'),(array)$email_config));`

Otherwise `$ci_email_config` is true, the config was indeed loaded.

Beside, If you set the config/email.php there should be no need to initialize. But you cant merge if you dont keep it.

So it should be 
`if ($ci_email_config) {
					$this->email->initialize(array_merge($this->config->item('email'),(array)$email_config));
				} else {
					$this->email->initialize((array)$email_config);
				}`

PS : this fix the next issue : https://github.com/benedmunds/CodeIgniter-Ion-Auth/issues/1344

**Comment by srok** [comment]
Looking at Email library, I guess the original code was just fine. Initialize method is additive, so 
`if ($this->config->item('use_ci_email', 'ion_auth') && isset($email_config) && is_array($email_config))
		{
			$this->email->initialize($email_config);
		}`
should work fine. I believe I was having another issue with config

**Comment by benedmunds** [comment]
Ah good to know, I'll revert this

**Comment by benedmunds** [comment]
@reno3131 can you test now that its reverted?

**Comment by benedmunds** [comment]
Closing due to time elapsed since the last response.  Please submit a new ticket if this is still an issue.
