### ISSUE TITLE
Email configuration file does not exist

### ISSUE THREAD

**Issue by imahtsham** [benedmunds/CodeIgniter-Ion-Auth#1344]
**This Github Issue section is meant to track bugs with the library itself**
Please post generic support issues to the CodeIgniter forums or StackOverflow.

After upgrading from version 2 to 3 i am getting this error "The configuration file email.php does not exist" Already Replace the files with the new files. Could you please help me out to figure out this problem. Thanks

**Comment by benedmunds** [comment]
@ProDev72 this should be fixed now, can you try again?

**Comment by niconeo33770** [comment]
Hi,

I have the same problem, I don't know where I can find the email.php config file. I have no error message but no email sending to activate account or forget password. I suppose the problem come from this file ?

No email.php config file here : 
- https://github.com/bcit-ci/CodeIgniter/tree/develop/application/config
- https://github.com/benedmunds/CodeIgniter-Ion-Auth/tree/3/config

Could you help me with this please ?

**Comment by bvrignaud** [comment]
Hello,

As the [documentation](https://codeigniter.com/user_guide/libraries/email.html#setting-email-preferences-in-a-config-file) explain, you have to create this file yourself.

**Comment by niconeo33770** [comment]
Thank you for your answer, I had indeed not read all the documentation on this part. My mistake. However I did not read this part because sending mail with CodeIgniter works without a configuration file because it uses my default php configuration it seems to me. Here is a test with CodeIgniter to prove it. 

I also read this documentation (http://benedmunds.com/ion_auth/) but I can not find where the problem comes from. below my ion_auth.php configuration. Do you know why the mails of ion_auth do not work, it seems to me to have well configured everything nevertheless.

Test_mail with CodeIgniter - OK
`<?php
        class Test_mail extends CI_Controller
        {
                public function index()
                {
                    $this->load->library('email');

                    $this->email->from('contact@aaa.fr', 'gml');
                    $this->email->to('nicolas@bbb.fr');
                    
                    $this->email->subject('Email Test');
                    $this->email->message('Testing the email class.');
                    
                    $this->email->send();
                }
        }
?>`

The mail.info log file OK : The email is correctly sent, I received it
`Nov 27 14:52:06 dev postfix/cleanup[31587]: 8B171E1111: message-id=<5dde8d965fee4@aaa.fr>
Nov 27 14:52:06 dev postfix/qmgr[26164]: 8B171E1111: from=<contact@aaa.fr>, size=561, nrcpt=1 (queue active)
Nov 27 14:52:07 dev postfix/smtp[31589]: 8B171E1111: to=<nicolas@bbb.fr>, relay=aspmx.l.google.com[64.233.167.26]:25, delay=1.1, delays=0.29/0.01/0.26/0.52, dsn=2.0.0, status=sent (250 2.0.0 OK  1574866327 p2si11855207wro.124 - gsmtp)
Nov 27 14:52:07 dev postfix/qmgr[26164]: 8B171E1111: removed
`

If I try with ion_auth the interface informs me that the recovery email has been sent, but no mail is sent in the log or received in my mailbox
<img width="455" alt="Capture d’écran 2019-11-27 à 16 23 35" src="https://user-images.githubusercontent.com/17906905/69736187-4f9dcc80-1132-11ea-848e-44600d2a65f6.png">

I searched for "use_ci_email" and "email_config" in your documentation but I did not find anything in your documentation, and it is not easy to know how configured this part, I do not know how to do, or what me problematic. Can you help me please ?

ma configuration ion_auth.php
`$config['site_title']                 = "bbb.fr";       
$config['admin_email']                = "contact@bbb.fr"; 
$config['default_group']              = 'members';          
$config['admin_group']                = 'admin';             
$config['identity']                   = 'email';            
$config['min_password_length']        = 8;                  
$config['email_activation']           = TRUE;              
$config['manual_activation']          = FALSE;              
$config['remember_users']             = TRUE;               
$config['user_expire']                = 86500;               
$config['user_extend_on_login']       = FALSE;               
$config['track_login_attempts']       = TRUE;                
$config['track_login_ip_address']     = TRUE;               
$config['maximum_login_attempts']     = 3;                   
$config['lockout_time']               = 600;                
$config['forgot_password_expiration'] = 1800;               
$config['recheck_timer']              = 0;                  

...

 | -------------------------------------------------------------------------
 | Email options.
 | -------------------------------------------------------------------------
 | email_config:
 | 	  'file' = Use the default CI config or use from a config file
 | 	  array  = Manually set your email config settings
 */
$config['use_ci_email'] = TRUE; //I also tried with FALSE  // Send Email using the builtin CI email class, if false it will return the code and the identity
$config['email_config'] = [
	'mailtype' => 'html',
];`

I don't understand the "email_config" and the option information. I did not find the settings in your documentation and we do not know or put 'file', I may be silly sorry.

**Comment by bvrignaud** [comment]
You're right, if sending email are OK outside IonAuth, I think that you don't need to set config/email.php.

Can you just try this in config/ion_auth.php:
```php
$config['use_ci_email'] = TRUE; // Send Email using the builtin CI email class, if false it will return the code and the identity
$config['email_config'] = [
	'mailtype' => 'html',
];
```
It's work for me in each of my project.

**Comment by niconeo33770** [comment]
Thank you for your answer, I had set this parameter to TRUE, but the file was not updated on my server! Sorry, thanks for your help! it's great, it works now.
