### ISSUE TITLE
Change email adres like tESt@gmail.com to test@gmail.com not working

### ISSUE THREAD

**Issue by bgougent** [benedmunds/CodeIgniter-Ion-Auth#1373]
Mentioned by a user - it's not a big deal but don't find it in the code why this behavior is.

She tried to change from LucZomergem@gmail.com  to luczomergem@gmail.com. It does not work.
With an extra step one can change the email
LucZomergem@gmail.com -> LucZomergem@gmail.co ->luczomergem@gmail.com.

I know that email will work with the capitals - just a technical question.

All email's are not real :-)

**Comment by benedmunds** [comment]
It's because we're checking to make sure that a user doesn't exist with the email already when a user tries to change their email: https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L1784

I'm not sure the best way to solve this really...  Maybe add a strtolower comparison and allow the change if it's the same email address.

**Comment by benedmunds** [comment]
Closing due to time elapsed since the last response.  Please submit a new ticket if this is still an issue.
