### ISSUE TITLE
Also track forgot password attempt

### ISSUE THREAD

**Issue by agung-wete** [benedmunds/CodeIgniter-Ion-Auth#1398]
**Which branch are you using?**
3

**What CodeIgniter version are you using?**
v3

**Describe the ~~bug~~ idea**
Its not bug, just idea. 
How about also track another endpoint other than login, like forgot password, reset etc
You know, to prevent abuse

Thank you

**Comment by benedmunds** [comment]
Hey, thanks for the suggestion.  Is there an attack vector you are aware of from the other endpoints?

I'll leave this open for others to comment on as well.

**Comment by agung-wete** [comment]
CMIIW
Someone can abuse forgot password feature, because its send email to user, also it still do hash computation that might be expensive depends on ion auth config/ hardware

**Comment by benedmunds** [comment]
We only send the email once per reset so I don't think there's much risk here. Unless someone were to brute force emails.  I'm definitely not against adding this though if you want to send a PR.

Closing this for now since it's not an issue.  But I definitely encourage you to submit a PR for review.  Thanks!
