### ISSUE TITLE
Resending activation email

### ISSUE THREAD

**Issue by nuryagdym** [benedmunds/CodeIgniter-Ion-Auth#1418]
Hello, 
I am using Ion Auth v3 with CI v3.
The problem I want to state is not a bug.
When user registers, I redirect him to a page where he can resend the activation email in case if he did not receive it. I guess there a lot of websites allow users to resend the activation email.
However, in user table Ion Auth does not keep the _validator_ field that it uses for user activation, it only keeps the hashed version of the _validator_ . 
So in order to resend the activation email, I will need to either
1. save activation code in SESSION (which is not possible if I use this library on Restful backend)
2. I will need to run the  `deactivate ` method to regenerate activation code (which will make the first activation code sent invalid)

So both options are not meaningful I guess. Why don't we just record the plain version of _validator_ code? As it is not a password I guess there are won't be any harm saving it in 
plain text (without hashing it)

**Comment by benedmunds** [comment]
They are separated in order to keep the selector/validator/hash separate in case the DB is leaked.  It mitigates an exploit where someone could recreate activation links just via the DB, thus gaining access any deactivated account if they have access to the DB.

Option #2 above is what I would recommend.
