### ISSUE TITLE
What are the reasons for having one user table for all?

### ISSUE THREAD

**Issue by ghost** [benedmunds/CodeIgniter-Ion-Auth#1432]
Hello,

I'm new to CI and I just found out Ion-Auth. This library is timesaver and I'm enjoy working with it. I just have a question about your DB design. 

You chose to have one User table for any type of user (customer, staff, admin...). During my research I found that a lot of people defend the idea of having different tables for different user types. One of the main reasons is scalability. Some people say that having one big user table will make queries slow. What's your thoughts about it?

Thank you!

**Comment by benedmunds** [comment]
Hey,

It's a tradeoff either way.  It is true that once an app is hitting huge scale there's a good chance you'll have to de-normalize the database.  That will apply to more than just users.

Most people aren't running apps at massive scale and once they are it's possible for them to refactor based on their exact needs.  Rather than trying to prematurely optimize, I decided to make the library simple and usable for 99% of our developers.

Once you get to large scale, I'm happy to help you optimize and refactor further.
