### ISSUE TITLE
The number of logged in users or even the list of logged in

### ISSUE THREAD

**Issue by fofopp** [benedmunds/CodeIgniter-Ion-Auth#1556]
The number of logged in users or even the list of logged in.

Is it possible to extract this information from IonAuth?

**Comment by benedmunds** [comment]
Ion Auth doesn’t have a way to do that built in, it’s almost impossible to know since users will close the browser without logging out.  You could probably use CI’s table based sessions and approximate who is logged in.  Or write a date time to the users table on each user activity throughout the site, then have logic to only count recent activity as active.
