### ISSUE TITLE
logged_in() not working correctly ? 

### ISSUE THREAD

**Issue by tokoapin** [benedmunds/CodeIgniter-Ion-Auth#453]
I think logged_in function should check with 

```
return (bool) $this->session->userdata('identity');
```

instead of 

```
return (bool) $this->session->userdata($identity);
```

The set_session() function is : 

```
    public function set_session($user)
{

    $this->trigger_events('pre_set_session');

    $session_data = array(
        'identity'             => $user->{$this->identity_column},
        'username'             => $user->username,
        'email'                => $user->email,
        'user_id'              => $user->iduser, //everyone likes to overwrite id so we'll use user_id
        'old_last_login'       => $user->last_login
    );

    $this->session->set_userdata($session_data);

    $this->trigger_events('post_set_session');

    return TRUE;
}
```

Clearly that it stores session name as 'identity', not the "identity_column name" in config file.

Am I missing something ? 
Best Regard, 
Tokoapin

**Comment by MasterJames** [comment]
It seems in my particular case, (when picking up the pieces from someone else's convolutions,) that the ajax calls where losing the session because they where rerouted to the domain name and not using the actual dev server (accessed via IP).

When I installed a DNS locally on the Dev deployment test machine so the domain could be used instead of that local VM's IP in the main URL, then the problem was resolved.

It's an older version and source (3rd party libs) running on a new server etc.
