### ISSUE TITLE
Can't login after installing Ion-Auth

### ISSUE THREAD

**Issue by vschaefer** [benedmunds/CodeIgniter-Ion-Auth#766]
Hello,

after installing Ion-Auth I have a Problem with the login. When I click on the login button CI shows the following error:

Error Number: 1054

Unknown column 'password' in 'field list'

SELECT email, username, email, password, id, active, last_login FROM (users) WHERE email = 'admin@admin.com' ORDER BY id desc LIMIT 1

The database looks correct. Does anyone have an idea what is wrong?

**Comment by agultekin** [comment]
Hello,

The problem seems to be from the default password generated by sha1.
In fact in the function verify in Bcrypt.php the calculated sha is not the same that inserted in the migration file.
To correct this problem you should change the password column value of admin@admin.com by the value : 59zE6QwGByDHk in your database 

It should help you. If the sha1 is not good go in the Bcrypt.php file and look in the function verify.

**Comment by vschaefer** [comment]
I have already solved the problem. I had remains of the bonfire framework on my server which I used once. That was the cause of the problem. Nevertheless many thanks :)
