### ISSUE TITLE
Username Identity Issue

### ISSUE THREAD

**Issue by usamacode** [benedmunds/CodeIgniter-Ion-Auth#933]
Please guys be noted that, If you set the Identity column to be username, your username will be empty when you are creating user.
Solution:-
Open Ion_Auth_Model.php and got to register function line 909 and remove username => '' from the $data array();
$data = array(
            $this->identity_column   => $identity,
            //'username' => '',
            'password'   => $password,
            'email'      => $email,
            'ip_address' => $ip_address,
            'created_on' => time(),
            'active'     => ($manual_activation === false ? 1 : 0)
        );

**Comment by avenirer** [comment]
@usamacode I don't know what version of Ion Auth you had, but the actual version has no code like that at that line...

**Comment by deusoz** [comment]
The 'register()' usage example shows: 
        $username = 'benedmunds'; 
                $password = '12345678';
        $email = 'ben.edmunds@gmail.com';
  ...   $this->ion_auth->register($username, $password, $email, $additional_data, $group);

Using the app as downloaded, "username" will NOT get saved to the user table using this example.

In order to make this example work, change the config['identity'] from 'email' to 'password' and add a Unique index to the username column in the user table.  

Being that it's safer to use unique username rather than email as login identity, this would be a worthy fix

**Comment by avenirer** [comment]
@deusoz I really don't understand how you've met those problems. Do you have the latest versions of the library, config and model?

Also, I don't understand why you think that it's saver to use unique username rather than email, which was also unique last time I checked...

**Comment by usamacode** [comment]
Yes, @avenirer , as per the TO DO in the model it shows "Version: 2.5.2" and I've commented the line of 'username' => '' under "// Users table." section.

Thanks,

**Comment by deusoz** [comment]
Hi,

I just downloaded app last week from GitHub.

As for emails as usernames, I'm not sure why, but some companies are no 
longer allowing emails to be used as usernames.  I suppose since the 
username/password can be considered as 2 hurdles to the account, if you 
know that John Doe only uses john.doe@gmail.com as his email and you 
want to hack his account, you already have the first hurdle crossed if 
the norm for that company is to use email as username. I suppose it's 
arguable, but I've taken to that premise and even encrypt usernames just 
like passwords for one high security site I manage.

Best regards,
Stuart
