### ISSUE TITLE
Is it possible to check multiple conditions?

### ISSUE THREAD

**Issue by ghost** [benedmunds/CodeIgniter-Ion-Auth#994]
I am trying to check if a user is logged in AND has admin-status (vs normal user) to route to different admin areas:

```
    public function index()
    {
        if ($this->ion_auth->logged_in() && $this->ion_auth->is_admin())
        {
            redirect('admin');
        } elseif ($this->ion_auth->logged_in() && ! $this->ion_auth->is_admin()) {
            redirect('user');
        } else {
            redirect('auth/login');
        }
    }
```

However, it looks like only the first part is checked (logged_in) and the second part after the && is never evaluated.

Is it possible to check multiple conditions at the same time?

**Comment by avenirer** [comment]
It is not possible for the PHP to only check the first part of the AND condition. So the problem is somewhere else. That code is perfectly valid. Anyway, not really related to your "problem", if a user is_admin, he is also logged_in. So the first condition should be to check only if the user is admin. The elseif should then check if the user is logged_in.

``` php
public function index()
    {
        if ($this->ion_auth->is_admin())
        {
            redirect('admin');
        } elseif ($this->ion_auth->logged_in()) {
            redirect('user');
        } else {
            redirect('auth/login');
        }
    }
```

**Comment by lloricode** [comment]
the **first** condition is will be executed if the login user has both user_group(`admin and member`).
the **second**  condition will be executed when `member only`.
